#! /bin/sh

sxhkd &

xsetroot -cursor_name left_ptr &
nitrogen --restore &
compton &

$HOME/.config/polybar/launch.sh

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Code desktop='^3'
bspc rule -a Firefox desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Launch the terminal
xfce4-terminal
